### ISSUE TITLE
I'd like to contribute! I have a one question though...

### ISSUE THREAD

**Issue by massivelivefun** [petertseng/exercism-zig#1]
I have a large amount of exercises written in Zig right now that are nearly ready to go!

Before setting up a pull request though I realized that exercises need to be added into the config.json file. The attributes of each exercise are pretty self explanatory as I have experience with a lot of exercism tracks. I just have one question regarding those attributes: how are the uuids generated for each exercise in the config.json? If that method of generation can be illuminated then I can contribute my plethora of exercises with the appropriate changes to the config.json.

However, my question above is running under the assumption that anyone can change that file. If only "project maintainers" are allowed to alter that file, then I'm more than happy to contribute just the exercise files.

**Comment by petertseng** [comment]
Thanks for your interest! First I will answer your most immediate questions, then I will advise on how I think things should proceed from here.

To my knowledge, you may use *any* tool that generates a valid version 4 UUID. I know this because the officially-blessed tool https://github.com/exercism/configlet/blob/master/cmd/uuid.go uses https://godoc.org/github.com/google/uuid#New, which generates version 4 UUIDs. You may use that tool, or any other tool (I searched online for "random uuid" and found a webpage that generates UUIDs).

The person who contributes an exercise is allowed to change config.json as appropriate. So you should feel free to do that.

As for how I think things should proceed:

I am not running this track in any official Exercism capacity; this was a personal experiment only. Therefore, I think it is not necessary for me to gatekeep contributions you wish to make. And I lack the time and attention to do that. I would only slow you down, and I absolutely do not want to slow you down or get in the way of your contributing!

So I think you are going to want to open an issue at https://github.com/exercism/request-new-language-track/issues/new, to say you want to work on a new Zig track. There is not currently an official Exercism Zig track (https://github.com/exercism/zig), so someone does need to request it if there is to eventually be one. You are free to use any of the information I filled out in https://github.com/exercism/request-new-language-track/issues/75 (or not, since I filled that issue out with very little knowledge). You are also free to cherry-pick commits and/or copy content from this repo into the new track.

If you want to wait until you have a more substantial body of exercises built up before making that request, there definitely is the possibility of continuing to add them to your fork of this repo.

If you are like me and lack the time to be the person to maintain the track and just want to contribute exercises ready for use by a person who eventually will maintain it, you could continue to do your work in your repo and then link your repo in https://github.com/exercism/request-new-language-track/issues/75, for the next person to find and pick up.

If you want to get in touch with other Exercism track maintainers, I think if you make an issue at either https://github.com/exercism/request-new-language-track/issues/new or https://github.com/exercism/exercism/issues/new, iHiD can put you in touch.

I hope I was able to paint at least a somewhat-clear picture of the path forward. Let me know if you have any questions!

**Comment by massivelivefun** [comment]
Okay, I'll continue my work on my fork at https://github.com/massivelivefun/exercism-zig, and hopefully my efforts will get on the Zig track, if it'll exist. As for being a maintainer, I don't completely understand the level of commitment that involves, so I'm not sure about it. I'll ask about that aspect in the Zig new language proposal in exercism/request-new-language-track#75, and try to get in contact with some track maintainers as well.

Otherwise thanks for the advice!
